/*
drop table if exists users CASCADE;
create table users (
    user_id integer generated by default as identity,
    about_me varchar(255),
    email varchar(255),
    interest_framework varchar(255),
    interest_job varchar(255),
    interest_language varchar(255),
    join_date date,
    location1 varchar(255),
    location2 varchar(255),
    name varchar(255),
    nickname varchar(255),
    password varchar(255),
    profile_content varchar(255),
    profile_photo varbinary(255),
    primary key (user_id)
);
/*
drop table if exists meeting CASCADE;
create table meeting (
    meeting_id integer generated by default as identity,
    application_count integer not null,
    application_deadline date,
    category integer not null,
    creation_date date,
    deleted integer default 0 not null,
    description varchar(255),
    interest_framework varchar(255),
    interest_job varchar(255),
    interest_language varchar(255),
    location varchar(255),
    recruitment_count integer not null,
    status integer not null,
    title varchar(255),
    views integer default 0 not null,
    user_id integer,
    primary key (meeting_id)
)
*/

/*
drop table if exists item CASCADE;
create table item (
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);
*/
